seed: 657838
gpu: true

dataset:
  name: oxymoron
  path: oxymoron.jsonl
  split:
    train: 0.8
    dev: 0.1
    test: 0.1
  max_length: 35

model:
  type: pythia
  name: EleutherAI/pythia-160m
  freeze: 1
  sentence_rep: hs-mean
  layer: 6

regimen:
  inds: 0.001,0.002,0.004,0.008,0.016,0.032,0.0625,0.125,0.25,0.5,1

probe:
  hidden_dim: 256
  probe_hidden_layers: 1
  dropout: 0
  params_path: probe.params
  
probe_training:
  batch_size: 20
  epochs: 40
  loss: cross-entropy
  weight_decay: 0.0
  learning_rate: 0.0001
  wait_without_improvement_for: 4
  
reporting:
  root: ../report
  reporting_methods:
    - label_accuracy
    - f1_class

trajectories:
  every: 1000
  first_steps: 0,1,2,4,8,16,32,64,128,256,512,1000
  total: 154